version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./conf/db_password:/mysqlpwd
      - ./conf/db_init:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /mysqlpwd
      MARIADB_DATABASE: secrets
    cpus: 1
    pids_limit: 256
    mem_limit: 512m
  
  api:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./conf/db_password:/dbpassword
    cpus: 1
    pids_limit: 256
    mem_limit: 512m

  nginx:
    image: openresty/openresty:1.21.4.1-buster-fat
    restart: unless-stopped
    ports:
      - "3355:80"
    volumes:
      - ./front:/front
      - ./conf/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/proxy_params:/usr/local/openresty/nginx/conf/proxy_params
    mem_limit: 256m
    pids_limit: 1024
    cpus: 1
